/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author CORE
 */
public class UpdateDonee extends javax.swing.JFrame {
    String getDate = "",getTime = "";
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
int cycle = 1;
             String fname = "";
             String mname = "";
             String lname = "";
             String donorsID = "";
            String getAplus = "";
            String getAneg = "";
            String getBplus = "";
            String getBneg = "";
            String getABplus = "";
            String getABneg = "";
            String getOplus = "";
            String getOneg = "";
            int StockInc = 1;
    /**
     * Creates new form Main
     */
    public UpdateDonee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblSelectedRowDoneeID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtMname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        cboGender = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboBloodType = new javax.swing.JComboBox<>();
        txtReceivedDate = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField11 = new com.toedter.calendar.JDateChooser();
        jTextField12 = new javax.swing.JTextField();
        lblDoneeID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cboBloodNeed = new javax.swing.JComboBox<>();
        txtPurpose = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField15 = new com.toedter.calendar.JDateChooser();
        jTextField16 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Bank ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UPDATE DONEE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 0, 270, 40);

        lblSelectedRowDoneeID.setForeground(new java.awt.Color(153, 0, 0));
        lblSelectedRowDoneeID.setText("DoneeID");
        lblSelectedRowDoneeID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblSelectedRowDoneeIDPropertyChange(evt);
            }
        });
        jPanel1.add(lblSelectedRowDoneeID);
        lblSelectedRowDoneeID.setBounds(620, 20, 50, 14);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodbank/image/backbutton.png"))); // NOI18N
        jLabel9.setToolTipText("Back");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 50, 40);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONAL INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Middle Name");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 100, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(40, 130, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(40, 160, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 190, 90, 30);

        txtFname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtFname);
        txtFname.setBounds(140, 70, 190, 30);

        txtMname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtMname);
        txtMname.setBounds(140, 100, 190, 30);

        txtLname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtLname);
        txtLname.setBounds(140, 130, 190, 30);

        txtAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel3.add(txtAge);
        txtAge.setBounds(140, 160, 90, 30);

        cboGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(cboGender);
        cboGender.setBounds(140, 190, 90, 30);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 30, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Contact No.");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 60, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("e-Mail");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(50, 90, 50, 30);

        txtAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtAdd);
        txtAdd.setBounds(110, 30, 190, 30);

        txtContactNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(txtContactNo);
        txtContactNo.setBounds(110, 60, 190, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail);
        txtEmail.setBounds(110, 90, 190, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(30, 230, 320, 130);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLOOD DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Blood Type");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 30, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Received Date");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 70, 100, 30);

        cboBloodType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboBloodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blood Type", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cboBloodType.setEnabled(false);
        cboBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBloodTypeActionPerformed(evt);
            }
        });
        jPanel5.add(cboBloodType);
        cboBloodType.setBounds(120, 30, 150, 30);

        txtReceivedDate.setDateFormatString("yyyy-MM-dd");
        txtReceivedDate.setEnabled(false);
        jPanel5.add(txtReceivedDate);
        txtReceivedDate.setBounds(120, 70, 150, 30);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLOOD DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Purpose");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 110, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Blood Type");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(10, 30, 100, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Donate Date");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(10, 70, 100, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blood Type", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel6.add(jComboBox3);
        jComboBox3.setBounds(120, 30, 150, 30);

        jTextField11.setDateFormatString("yyyy-MM-dd");
        jPanel6.add(jTextField11);
        jTextField11.setBounds(120, 70, 150, 30);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField12);
        jTextField12.setBounds(120, 110, 150, 30);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(360, 20, 290, 160);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(360, 20, 290, 120);

        lblDoneeID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDoneeID.setText("DonneID");
        jPanel3.add(lblDoneeID);
        lblDoneeID.setBounds(140, 30, 140, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("UPDATE DONEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(470, 300, 180, 40);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLOOD NEEDED", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel7.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Purpose");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(10, 70, 100, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Blood Type");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(10, 30, 100, 30);

        cboBloodNeed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboBloodNeed.setEnabled(false);
        jPanel7.add(cboBloodNeed);
        cboBloodNeed.setBounds(120, 30, 150, 30);

        txtPurpose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPurpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurposeActionPerformed(evt);
            }
        });
        jPanel7.add(txtPurpose);
        txtPurpose.setBounds(120, 70, 150, 30);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BLOOD DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel8.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Purpose");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(10, 110, 100, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Blood Type");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(10, 30, 100, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Donate Date");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(10, 70, 100, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blood Type", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel8.add(jComboBox5);
        jComboBox5.setBounds(120, 30, 150, 30);

        jTextField15.setDateFormatString("yyyy-MM-dd");
        jPanel8.add(jTextField15);
        jTextField15.setBounds(120, 70, 150, 30);

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField16);
        jTextField16.setBounds(120, 110, 150, 30);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(360, 20, 290, 160);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(360, 160, 290, 120);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("First Name");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(40, 70, 140, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("First Name");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(40, 30, 140, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 680, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (txtFname.getText().equals("") || txtMname.getText().equals("") || txtLname.getText().equals("") || txtAge.getText().equals("") || txtAdd.getText().equals("") || txtContactNo.getText().equals("") || txtEmail.getText().equals("") || ((JTextField)txtReceivedDate.getDateEditor().getUiComponent()).getText().equals("") || cboBloodNeed.getSelectedItem().equals(null)){
        JOptionPane.showMessageDialog(null, "Fill up all Fields","Blood Bank System",JOptionPane.ERROR_MESSAGE);
        }else{
             if(cboBloodType.getSelectedItem().equals("Blood Type")){
                JOptionPane.showMessageDialog(null, "Select Blood Type");
             }else{
                 try{
                conn=SQLCon.ConnectDB();
                String sql  = "UPDATE donee SET fName='"+txtFname.getText()+"',mName='"+txtMname.getText()+"',lName='"+txtLname.getText()+"',age='"+txtAge.getText()+"',gender='"+cboGender.getSelectedItem()+"',address='"+txtAdd.getText()+"',contactNo='"+txtContactNo.getText()+"',eMail='"+txtEmail.getText()+"',bloodType='"+cboBloodType.getSelectedItem()+"',receivedDate='"+((JTextField)txtReceivedDate.getDateEditor().getUiComponent()).getText()+"',bloodTypeNeed='"+cboBloodNeed.getSelectedItem()+"',purpose='"+txtPurpose.getText()+"' WHERE doneeID='"+lblSelectedRowDoneeID.getText()+"'";
             pst=conn.prepareStatement(sql);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Donee Successfully Updated");
                 }catch(Exception e){
                     JOptionPane.showMessageDialog(null, e);
                 }
             }
             cboBloodType.requestFocus();
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void txtPurposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurposeActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void cboBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBloodTypeActionPerformed
        // TODO add your handling code here:
        if(cboBloodType.getSelectedItem().equals("A+")){
        cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("A+");
        cboBloodNeed.addItem("A-");
        cboBloodNeed.addItem("O+");
        cboBloodNeed.addItem("O-");
        }else if(cboBloodType.getSelectedItem().equals("A-")){
        cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("A-");
        cboBloodNeed.addItem("O-");
        }else if(cboBloodType.getSelectedItem().equals("B+")){
        cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("B+");
        cboBloodNeed.addItem("B-");
        cboBloodNeed.addItem("O+");
        cboBloodNeed.addItem("O-");
        }else if(cboBloodType.getSelectedItem().equals("B-")){
        cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("B-");
        cboBloodNeed.addItem("O-");
        }else if(cboBloodType.getSelectedItem().equals("AB+")){
            cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("A+");
        cboBloodNeed.addItem("A-");
        cboBloodNeed.addItem("B+");
        cboBloodNeed.addItem("B-");
        cboBloodNeed.addItem("AB+");
        cboBloodNeed.addItem("AB-");
        cboBloodNeed.addItem("O+");
        cboBloodNeed.addItem("O-");
        }else if(cboBloodType.getSelectedItem().equals("AB+")){
            cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("A-");
        cboBloodNeed.addItem("B-");
        cboBloodNeed.addItem("AB-");
        cboBloodNeed.addItem("O-");
        }else if(cboBloodType.getSelectedItem().equals("O+")){
            cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("O+");
        cboBloodNeed.addItem("O-");
        }else if(cboBloodType.getSelectedItem().equals("O-")){
            cboBloodNeed.removeAllItems();
        cboBloodNeed.addItem("O-");
        }
    }//GEN-LAST:event_cboBloodTypeActionPerformed

    private void lblSelectedRowDoneeIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblSelectedRowDoneeIDPropertyChange
        // TODO add your handling code here:
        try{
            conn=MySqlConnectBAK.ConnectDB();
            String sql = "SELECT * FROM `donee` WHERE `doneeID`='"+lblSelectedRowDoneeID.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                lblDoneeID.setText(rs.getString("doneeID"));
                txtFname.setText(rs.getString("fName"));
                txtMname.setText(rs.getString("mName"));
                txtLname.setText(rs.getString("lName"));
                txtAge.setText(rs.getString("age"));
                cboGender.setSelectedItem(rs.getString("gender"));
                txtAdd.setText(rs.getString("address"));
                txtContactNo.setText(rs.getString("contactNo"));
                txtEmail.setText(rs.getString("eMail"));
                cboBloodType.setSelectedItem(rs.getString("bloodType"));
                txtReceivedDate.setDate(rs.getDate("receivedDate"));
                cboBloodNeed.setSelectedItem(rs.getString("bloodTypeNeed"));
                txtPurpose.setText(rs.getString("purpose"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lblSelectedRowDoneeIDPropertyChange

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new Donee().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDonee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDonee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDonee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDonee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDonee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboBloodNeed;
    private javax.swing.JComboBox<String> cboBloodType;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jTextField11;
    private javax.swing.JTextField jTextField12;
    private com.toedter.calendar.JDateChooser jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JLabel lblDoneeID;
    public static javax.swing.JLabel lblSelectedRowDoneeID;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtPurpose;
    private com.toedter.calendar.JDateChooser txtReceivedDate;
    // End of variables declaration//GEN-END:variables

}
